TeamNaach/TeamNaach/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',article_views.articles_list, name="home"),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TeamNaach/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns=[
  path('signup/',views.signup_view, name="signup"),
  path('logout/',views.logout_view, name="logout"),
]

TeamNaach/articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.articles_list,name="list"),
    path('loggedin',views.logged_in, name="loggedin"),
    path('create',views.article_create, name="create"),
    path('<slug:slog>/edit/', views.edit_post, name="edit"),
    path('<slug:slog>/delete/', views.delete_post, name="delete"),
    path('<str:slog>/', views.article_detail, name="detail"),
]

TeamNaach/accounts/models.py
from django.db import models

# Create your models here.

TeamNaach/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title= models.CharField(max_length=140)
    slog=models.SlugField(max_length=250, unique=True)
    body=models.TextField()
    date= models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='default.jpg', blank=True)
    author= models.ForeignKey(User,default= None, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+"..."

TeamNaach/articles/forms.py
from django import forms
from .import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title', 'body', 'slog', 'thumb']

TeamNaach/TeamNaach/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

TeamNaach/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,logout
# Create your views here.
def signup_view(request):
    if request.method=='POST':
        form= UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            #log the user in
            login(request,user)
            return redirect('loggedin')
    else:
        form= UserCreationForm()
    return render(request, 'accounts/signup.html',{'form': form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect("list")

TeamNaach/articles/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from .import forms
from django.contrib import messages
from django.urls import reverse
# Create your views here.

def articles_list(request):
    if request.method =='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            articles= Article.objects.all().order_by('date')
            return render(request,"articles/loggedin.html", {'User' :user, 'articles':articles })
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

    else:
        form=AuthenticationForm()

    articles= Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles': articles, 'form':form})

def article_detail(request, slog):
    article= Article.objects.get(slog=slog)
    user= request.user
    return render(request, 'articles/article-detail.html',{'article':article, 'user':user})

@login_required(login_url="/articles")
def logged_in(request):
    user=request.user
    articles=Article.objects.all().order_by('date')
    return render(request,"articles/loggedin.html", {'User' :user, 'articles':articles })

@login_required(login_url="/articles")
def article_create(request):
    if request.method=="POST":
        form=forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect("detail", slog=instance.slog)
    else:
        form= forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

def edit_post(request, slog):
 template= 'articles/article_create.html'
 post= get_object_or_404(Article,slog=slog)
 if request.user==post.author:
    if request.method== 'POST':
        form= forms.CreateArticle(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post= form.save(commit=False)
            post.author= request.user
            post.save()
            messages.success(request,"Your blog has been editted!")
            return redirect("detail", slog=post.slog)
    else:
        form=forms.CreateArticle(instance=post)
    return render(request, template,{'form':form})
 else:
     messages.success(request,"You can only edit your blogs!")
     return redirect("loggedin")

def delete_post(request, slog):
    post=get_object_or_404(Article, slog=slog)
    post.delete()
    messages.success(request, "Successfully Deleted")
    return redirect('loggedin')

TeamNaach/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>SIGNUP</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
  <input type="submit" value="Signup">
  </form>
{% endblock %}

TeamNaach/articles/templates/articles/article-detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
  <div class='article'>
    <img src="{{article.thumb.url}}", height='300', width='800'/>
    <h2>{{article.title}}</h2>
    <p style= overflow-x:hidden >{{article.body}}</p>
    <p>{{article.date}}</p>
    {% if user.is_authenticated %}
      <p><a href="{% url 'edit' slog=article.slog %}">EDIT</a></p>
      <p><a href="{% url 'delete' slog=article.slog %}">DELETE</a></p>
    {% endif %}
  </div>
</div>

{% endblock %}

TeamNaach/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
{% csrf_token %}
 <div class="create-article">
    <h2>Create an Awesome New Article</h2>
      <form class="site-form" method="post" enctype="multipart/form-data">
       {% csrf_token %}
       <input type="hidden" value="{{slog}}">
       {{form}}
      <input type="submit" value="SAVE">
     </form>
 </div>
 <script src="/static/slugify.js"></script>

{% endblock %}

TeamNaach/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<hr>
<div class="sit" align ="center">
   <h2> Log In</h2><br>
   <form class="col" method="post">
     {% csrf_token %}
     {{form}}
     {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
     {% endif %}
     <input type="submit" value="LogIn">
     </form>
</div><hr>
   <h2>Member's Blogs:</h2><br><br>
<div class="row">
  <div class="articles">
     {% for article in articles %}
      <div class="article">
        <h2><a href= "{% url 'detail' slog=article.slog %}"> {{article.title}}</a></h2>
        <p> {{article.snippet}}</p>
        <p> {{article.date}}</p>
        <p class="author" >added by {{ article.author.username }}</p>
        <br>
      </div>
     {% endfor %}
  </div>
  <hr>

{% endblock %}

TeamNaach/articles/templates/articles/loggedin.html
{% extends 'base_layout.html' %}

{% block content %}
{% csrf_token %}
  <h3>Let's add some blogs :) </h3>
  <br><br>
  <h2>Your Blogs:</h2>
    <div class="articles">
      {% for article in articles %}
       {% if article.author == User %}
        <div class="article">
         <h2><a href= "{% url 'detail' slog=article.slog %}"> {{article.title}}</a></h2>
         <p> {{article.snippet}}</p>
         <p> {{article.date}}</p>
         <br>
        {% endif %}
      {% endfor %}
    </div>
   </div>

{% endblock %}

TeamNaach/articles/templates/articles/messages.html
{% if messages %}
  {% for message in messages %}
   {% if message.tags %}<div class="alert alert-{{message.tags}}" style="background-color:red" align="center">{{message}}</div>
   {% endif %}
  {% endfor %}
{% endif %}

TeamNaach/templates/base_layout.html
{%load static %}

<!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8">
   <title>Articles</title>
   <link rel="stylesheet" href="{%static 'styles.css'%}" />
 </head>
 <body>
   <header class="wrapper">
     <h1><a href="{% url "home" %}"><img src="{% static 'logo.jpg' %}", height='120', width='120'></a></h1>
     <h2>Welcome To 'Team Naach' Community</h2>
     <nav>
       <ul>
         {% if user.is_authenticated %}
        <li>
         <form class="logout-link" action="{% url "accounts:logout" %}" method="post">
             {% csrf_token %}
             <button type="submit">LogOut</button>
         </form>
        </li>
        <li><a href="{% url 'create' %}" class="highlight">Add a new blog</a></li>
        <li><a href="{% url 'loggedin' %}">Dashboard</a></li>
         {% else %}
           <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
         {% endif %}
       </ul>
      </nav>
    </header>
    <div class="wrapper">
     {% include "articles/messages.html" %}
     {% block content %}
     {% endblock %}
    </div>
  </body>
</html>

TeamNaach/templates/homepage.html
<!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8">
   <title>Homepage</title>
 </head>
 <body>
   <h1> This </h1>
   <p> Welcome to Team Naach </p>
 </body>
</html>